/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ndk1_Simple6 */

#ifndef _Included_ndk1_Simple6
#define _Included_ndk1_Simple6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple6
 * Method:    createPoint
 * Signature: ()Lmodel/Point;
 */
JNIEXPORT jobject JNICALL Java_ndk1_Simple6_createPoint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
